### ISSUE TITLE
Implement social login buttons

### ISSUE THREAD

**Issue by qlereboursBS** [BearStudio/start-ui-web#324]
An issue I came across during the project I developed, is that creating or using social login buttons is a pain. Some of the social networks will give you the button, which is an image, some of them will have their own branding restrictions and so on.

It could be great to have some of the standard social platform buttons implemented.

**Comment by deelanM** [comment]
@qlereboursBS it seems react-icons, which is already installed within Start UI's dependencies, provides button icons for the most common options of SSO : https://chakra-templates.dev/components/social-media-buttons
I would suggest the following solution for this issue's scope : 
1. Add an "--OR--" separator inbetween the Password input and "Forgotten password" label (resembling Instagram's login form), followed by the different SSO buttons (Facebook, Google, LinkedIn)
![image](https://user-images.githubusercontent.com/73607425/209500617-b0444745-729e-4970-a13a-c885cdb4cc89.png)
![image](https://user-images.githubusercontent.com/73607425/209500786-7692bb2b-a415-4435-9001-23554c2ce9b2.png)

In coding terms, this would basically translate to : 
1. `components/LoginForm` : after the password's `FieldInput`, add a `Flex ` containing each SSO option's  `Button `   (each using the targeted social platform's icon from `react-icons`, obviously)

**Comment by deelanM** [comment]
@qlereboursBS and I discussed this issue IRL. We've come up with the suggestion that we should at least add some social media login button variations to the Button entry of the Storybook, as well as the Facebook and Google auth buttons to the `LoginForm`. This way, implementing one of those buttons becomes easily findable for anyone. 
The other issue that arises from this would be the API call these buttons should make : if we are to include a social media login button, should we integrate the boilerplate code required to make the matching call associated with said button ? Since this would require some backend setup as well... For example, Facebook requires creating a Facebook app, which provides an app ID required to authenticate via Facebook. We could make the argument that we could integrate this button along with the API call, and only the app ID would be required by anyone creating a project with Start UI. We think this should be discussed with main project maintainers before going any further...

**Comment by yoannfleurydev** [comment]
Won't do as 🚀 Start UI [web] and 🚀 Start UI [native] are quite linked and we want to keep it that way.

If you really want Single Sign On and won't use 🚀 Start UI [native], we highly recommend you to take a look at https://authjs.dev/
